package Backend.core.enums;

public enum JobPosition {
    // Yazılım Geliştirme
    SOFTWARE_ENGINEER,
    FRONTEND_DEVELOPER,
    BACKEND_DEVELOPER,
    FULLSTACK_DEVELOPER,
    MOBILE_DEVELOPER,
    GAME_DEVELOPER,
    EMBEDDED_SOFTWARE_ENGINEER,
    TEST_AUTOMATION_ENGINEER,

    // Veri ve Yapay Zeka
    DATA_SCIENTIST,
    DATA_ENGINEER,
    MACHINE_LEARNING_ENGINEER,
    AI_ENGINEER,
    COMPUTER_VISION_ENGINEER,
    NLP_ENGINEER,

    // Ürün ve Proje Yönetimi
    PRODUCT_MANAGER,
    PROJECT_MANAGER,
    SCRUM_MASTER,
    BUSINESS_ANALYST,
    TECHNICAL_PRODUCT_MANAGER,

    // Sistem ve Ağ
    SYSTEM_ADMINISTRATOR,
    NETWORK_ENGINEER,
    DEVOPS_ENGINEER,
    SITE_RELIABILITY_ENGINEER,
    CLOUD_ENGINEER,

    // Güvenlik ve Kalite
    CYBERSECURITY_SPECIALIST,
    SECURITY_ANALYST,
    SECURITY_ARCHITECT,
    QA_ENGINEER,
    PENETRATION_TESTER,

    // Tasarım ve Kullanıcı Deneyimi
    UX_UI_DESIGNER,
    GRAPHIC_DESIGNER,
    INTERACTION_DESIGNER,
    MOTION_GRAPHICS_DESIGNER,

    // Veri Tabanı ve Sistem Yönetimi
    DATABASE_ADMINISTRATOR,
    DATA_ARCHITECT,
    BIG_DATA_ENGINEER,
    ETL_DEVELOPER,

    // IT Destek ve Danışmanlık
    IT_SUPPORT_SPECIALIST,
    HELP_DESK_TECHNICIAN,
    IT_CONSULTANT,
    SYSTEMS_ANALYST,

    // Yeni Teknolojiler
    BLOCKCHAIN_DEVELOPER,
    IOT_DEVELOPER,
    ROBOTICS_ENGINEER,
    AR_VR_DEVELOPER,
    QUANTUM_COMPUTING_ENGINEER,

    // Eğitim ve Araştırma
    ACADEMIC_RESEARCHER,
    TECHNICAL_TRAINER,

    // Genel veya Özel Rollar
    FREELANCER,
    INTERN,
    OTHER
}
